### ISSUE TITLE
Error searching events

### ISSUE THREAD

**Issue by idevelopr** [ryanj/eventbrite.npm#2]
```
 var params = {'city': "San Francisco", 'region': "CA"};

eb_client.event_search( params, function(err, data){
    console.log(err);
    console.log(data);
});
 ```

> Error Type : **Request Error**

> Error message : **Not a valid API command . Please check documentation**

>

**Comment by ryanj** [comment]
@idevelopr This API client library targets the older (unavailable) version of the Eventbrite API.  I'd check Eventbrite's developer site to see if they have anything newer available.

Sorry, I'll add a deprecation notice to the README #3
